#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TodayILearned.AndroidApp.Resource", IsApplication=true)]

namespace TodayILearned.AndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int pref_textSizeValues = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int pref_textSizes = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_important = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_refresh = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_search = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_share = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080004
			public const int Image = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int Text = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int Text1 = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int Text2 = 2131230726;
			
			// aapt resource value: 0x7f080010
			public const int action_buy = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int action_search = 2131230735;
			
			// aapt resource value: 0x7f080011
			public const int action_settings = 2131230737;
			
			// aapt resource value: 0x7f080008
			public const int ad = 2131230728;
			
			// aapt resource value: 0x7f08000c
			public const int addFavourites = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int empty_id = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int list_container_id = 2131230730;
			
			// aapt resource value: 0x7f080000
			public const int pager = 2131230720;
			
			// aapt resource value: 0x7f080009
			public const int progress_container_id = 2131230729;
			
			// aapt resource value: 0x7f08000d
			public const int removeFavourites = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int share = 2131230734;
			
			// aapt resource value: 0x7f080007
			public const int throbber = 2131230727;
			
			// aapt resource value: 0x7f080001
			public const int titleTextView = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int webView = 2131230722;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int TriviaDetails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TriviaItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int TriviaList = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int DetailsMenu = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int MainMenu = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int Label = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int hint = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int medium = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int pref_sizeDialog = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int pref_sizeTitle = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int small = 2131099654;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int searchable = 2130968577;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
