#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TodayILearned.AndroidApp.Resource", IsApplication=true)]

namespace TodayILearned.AndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_important = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_search = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_share = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_popup_sync_1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public const int Image = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int Text = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int Text1 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int Text2 = 2131165190;
			
			// aapt resource value: 0x7f07000b
			public const int action_search = 2131165195;
			
			// aapt resource value: 0x7f070008
			public const int addFavourites = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int pager = 2131165184;
			
			// aapt resource value: 0x7f070009
			public const int removeFavourites = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int share = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int throbber = 2131165191;
			
			// aapt resource value: 0x7f070001
			public const int titleTextView = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int webView = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int TriviaDetails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TriviaItem = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int DetailsMenu = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int MainMenu = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int Label = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int hint = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int searchable = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
