//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodayILearned.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TodayILearned.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today I Learned.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODAY I LEARNED.
        /// </summary>
        public static string AppTitleCapitalized {
            get {
                return ResourceManager.GetString("AppTitleCapitalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by Dapper Panda.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose date.
        /// </summary>
        public static string ButtonChooseDate {
            get {
                return ResourceManager.GetString("ButtonChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email feedback.
        /// </summary>
        public static string ButtonFeedback {
            get {
                return ResourceManager.GetString("ButtonFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next day.
        /// </summary>
        public static string ButtonNextDay {
            get {
                return ResourceManager.GetString("ButtonNextDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        public static string ButtonPrevDay {
            get {
                return ResourceManager.GetString("ButtonPrevDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app.
        /// </summary>
        public static string ButtonRate {
            get {
                return ResourceManager.GetString("ButtonRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string ButtonToday {
            get {
                return ResourceManager.GetString("ButtonToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dapperpanda@gmail.com.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On This Day... is a simple app for viewing important events in history..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content is provided by Wikipedia. The application icon is by Icon8 (www.icons8.com).
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check On This Day... task under Settings &gt;Applications &gt;Background Tasks  Then restart the app and enable the live tile from the settings page..
        /// </summary>
        public static string ErrorCouldNotEnableLiveTileDescription {
            get {
                return ResourceManager.GetString("ErrorCouldNotEnableLiveTileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not enable the live tile.
        /// </summary>
        public static string ErrorCouldNotEnableLiveTileTitle {
            get {
                return ResourceManager.GetString("ErrorCouldNotEnableLiveTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection is not available.
        /// </summary>
        public static string ErrorInternetConnection {
            get {
                return ResourceManager.GetString("ErrorInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We would love to hear your comments about On This Day... Send us your thoughts.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback for On This Day....
        /// </summary>
        public static string FeedbackOn {
            get {
                return ResourceManager.GetString("FeedbackOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, I&apos;ve been using On This Day... app and I have the following feedback....
        /// </summary>
        public static string FeedbackTemplate {
            get {
                return ResourceManager.GetString("FeedbackTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome! Setting up now.
        /// </summary>
        public static string InitialLoadLowMemoryDevice {
            get {
                return ResourceManager.GetString("InitialLoadLowMemoryDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome! Setting up the live tile now.
        /// </summary>
        public static string InitialLoadRegularDevice {
            get {
                return ResourceManager.GetString("InitialLoadRegularDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string MenuItemAbout {
            get {
                return ResourceManager.GetString("MenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buy ad-free version.
        /// </summary>
        public static string MenuItemBuyAdFreeVersion {
            get {
                return ResourceManager.GetString("MenuItemBuyAdFreeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disable live tile.
        /// </summary>
        public static string MenuItemDisableLiveTile {
            get {
                return ResourceManager.GetString("MenuItemDisableLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable live tile.
        /// </summary>
        public static string MenuItemEnableLiveTile {
            get {
                return ResourceManager.GetString("MenuItemEnableLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calendar and birthdays.
        /// </summary>
        public static string MenuItemMyEvents {
            get {
                return ResourceManager.GetString("MenuItemMyEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate this app.
        /// </summary>
        public static string MenuItemRateThisApp {
            get {
                return ResourceManager.GetString("MenuItemRateThisApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string MenuItemSettings {
            get {
                return ResourceManager.GetString("MenuItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please take a moment to rate or review this app. We&apos;d love to hear from you..
        /// </summary>
        public static string MessageBoxRateThisAppSummary {
            get {
                return ResourceManager.GetString("MessageBoxRateThisAppSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate or review this app?.
        /// </summary>
        public static string MessageBoxRateThisAppTitle {
            get {
                return ResourceManager.GetString("MessageBoxRateThisAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string PageTitleAbout {
            get {
                return ResourceManager.GetString("PageTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string PageTitleSettings {
            get {
                return ResourceManager.GetString("PageTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to birthdays.
        /// </summary>
        public static string PivotTitleBirthdays {
            get {
                return ResourceManager.GetString("PivotTitleBirthdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to births.
        /// </summary>
        public static string PivotTitleBirths {
            get {
                return ResourceManager.GetString("PivotTitleBirths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calendar.
        /// </summary>
        public static string PivotTitleCalendar {
            get {
                return ResourceManager.GetString("PivotTitleCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deaths.
        /// </summary>
        public static string PivotTitleDeaths {
            get {
                return ResourceManager.GetString("PivotTitleDeaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events.
        /// </summary>
        public static string PivotTitleEvents {
            get {
                return ResourceManager.GetString("PivotTitleEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to highlights.
        /// </summary>
        public static string PivotTitleHighlights {
            get {
                return ResourceManager.GetString("PivotTitleHighlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to holidays.
        /// </summary>
        public static string PivotTitleHolidays {
            get {
                return ResourceManager.GetString("PivotTitleHolidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please rate and comment on this app in Marketplace.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size for descriptions.
        /// </summary>
        public static string SettingFontSize {
            get {
                return ResourceManager.GetString("SettingFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to large.
        /// </summary>
        public static string SettingFontSizeLarger {
            get {
                return ResourceManager.GetString("SettingFontSizeLarger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal.
        /// </summary>
        public static string SettingFontSizeNormal {
            get {
                return ResourceManager.GetString("SettingFontSizeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live tile.
        /// </summary>
        public static string SettingLiveTile {
            get {
                return ResourceManager.GetString("SettingLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to newest first.
        /// </summary>
        public static string SettingShowNewestFirst {
            get {
                return ResourceManager.GetString("SettingShowNewestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oldest first.
        /// </summary>
        public static string SettingShowOldestFirst {
            get {
                return ResourceManager.GetString("SettingShowOldestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order of events.
        /// </summary>
        public static string SettingSortOrder {
            get {
                return ResourceManager.GetString("SettingSortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.dapperpanda.com.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dapperpanda.com.
        /// </summary>
        public static string WebsiteWithHttp {
            get {
                return ResourceManager.GetString("WebsiteWithHttp", resourceCulture);
            }
        }
    }
}
