//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodayILearned.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TodayILearned.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trivia Buff.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRIVIA BUFF.
        /// </summary>
        public static string AppTitleCapitalized {
            get {
                return ResourceManager.GetString("AppTitleCapitalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by Dapper Panda.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email feedback.
        /// </summary>
        public static string ButtonFeedback {
            get {
                return ResourceManager.GetString("ButtonFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app.
        /// </summary>
        public static string ButtonRate {
            get {
                return ResourceManager.GetString("ButtonRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dapperpanda@gmail.com.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trivia Buff is a perfect app for trivia &amp; random fact lovers..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content is provided by reddit. If you would like to use a full featured reddit client, check out Baconit.
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check Trivia Buff task under Settings &gt;Applications &gt;Background Tasks  Then restart the app and enable the live tile from the settings page..
        /// </summary>
        public static string ErrorCouldNotEnableLiveTileDescription {
            get {
                return ResourceManager.GetString("ErrorCouldNotEnableLiveTileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not enable the live tile.
        /// </summary>
        public static string ErrorCouldNotEnableLiveTileTitle {
            get {
                return ResourceManager.GetString("ErrorCouldNotEnableLiveTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection is not available.
        /// </summary>
        public static string ErrorInternetConnection {
            get {
                return ResourceManager.GetString("ErrorInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check you internet connectivity or try again later....
        /// </summary>
        public static string ErrorSiteNotAvailableMessage {
            get {
                return ResourceManager.GetString("ErrorSiteNotAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is not available.
        /// </summary>
        public static string ErrorSiteNotAvailableTitle {
            get {
                return ResourceManager.GetString("ErrorSiteNotAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We would love to hear your comments about Trivia Buff. Send us your thoughts.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback for Trivia Buff.
        /// </summary>
        public static string FeedbackOn {
            get {
                return ResourceManager.GetString("FeedbackOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, I&apos;ve been using Trivia Buff app and I have the following feedback....
        /// </summary>
        public static string FeedbackTemplate {
            get {
                return ResourceManager.GetString("FeedbackTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome! Setting up now.
        /// </summary>
        public static string InitialLoadLowMemoryDevice {
            get {
                return ResourceManager.GetString("InitialLoadLowMemoryDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome! Setting up the live tile now.
        /// </summary>
        public static string InitialLoadRegularDevice {
            get {
                return ResourceManager.GetString("InitialLoadRegularDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string MenuItemAbout {
            get {
                return ResourceManager.GetString("MenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buy ad-free version.
        /// </summary>
        public static string MenuItemBuyAdFreeVersion {
            get {
                return ResourceManager.GetString("MenuItemBuyAdFreeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disable live tile.
        /// </summary>
        public static string MenuItemDisableLiveTile {
            get {
                return ResourceManager.GetString("MenuItemDisableLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable live tile.
        /// </summary>
        public static string MenuItemEnableLiveTile {
            get {
                return ResourceManager.GetString("MenuItemEnableLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate this app.
        /// </summary>
        public static string MenuItemRateThisApp {
            get {
                return ResourceManager.GetString("MenuItemRateThisApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string MenuItemSettings {
            get {
                return ResourceManager.GetString("MenuItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please buy an ad-free version to support the developers. Thank you for using Trivia Buff.
        /// </summary>
        public static string MessageBoxBuyThisAppSummary {
            get {
                return ResourceManager.GetString("MessageBoxBuyThisAppSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad-free version is available.
        /// </summary>
        public static string MessageBoxBuyThisAppTitle {
            get {
                return ResourceManager.GetString("MessageBoxBuyThisAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please take a moment to rate or review this app. We&apos;d love to hear from you..
        /// </summary>
        public static string MessageBoxRateThisAppSummary {
            get {
                return ResourceManager.GetString("MessageBoxRateThisAppSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate or review this app?.
        /// </summary>
        public static string MessageBoxRateThisAppTitle {
            get {
                return ResourceManager.GetString("MessageBoxRateThisAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string PageTitleAbout {
            get {
                return ResourceManager.GetString("PageTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH.
        /// </summary>
        public static string PageTitleSearch {
            get {
                return ResourceManager.GetString("PageTitleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string PageTitleSettings {
            get {
                return ResourceManager.GetString("PageTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHARE.
        /// </summary>
        public static string PageTitleShare {
            get {
                return ResourceManager.GetString("PageTitleShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please rate and comment on this app in Marketplace.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser selection.
        /// </summary>
        public static string SettingBrowserSelection {
            get {
                return ResourceManager.GetString("SettingBrowserSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to built-in browser.
        /// </summary>
        public static string SettingBuiltInBrowser {
            get {
                return ResourceManager.GetString("SettingBuiltInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string SettingFontSize {
            get {
                return ResourceManager.GetString("SettingFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to large.
        /// </summary>
        public static string SettingFontSizeLarger {
            get {
                return ResourceManager.GetString("SettingFontSizeLarger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal.
        /// </summary>
        public static string SettingFontSizeNormal {
            get {
                return ResourceManager.GetString("SettingFontSizeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internet explorer.
        /// </summary>
        public static string SettingInternetExplorer {
            get {
                return ResourceManager.GetString("SettingInternetExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live tile.
        /// </summary>
        public static string SettingLiveTile {
            get {
                return ResourceManager.GetString("SettingLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do not show.
        /// </summary>
        public static string SettingTileDoNotFlip {
            get {
                return ResourceManager.GetString("SettingTileDoNotFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back of the tile.
        /// </summary>
        public static string SettingTileOption {
            get {
                return ResourceManager.GetString("SettingTileOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show logo.
        /// </summary>
        public static string SettingTileShowLogo {
            get {
                return ResourceManager.GetString("SettingTileShowLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string ShareClipboard {
            get {
                return ResourceManager.GetString("ShareClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ShareEmail {
            get {
                return ResourceManager.GetString("ShareEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social networks.
        /// </summary>
        public static string ShareSocialNetwork {
            get {
                return ResourceManager.GetString("ShareSocialNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text message.
        /// </summary>
        public static string ShareTextMessaging {
            get {
                return ResourceManager.GetString("ShareTextMessaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.dapperpanda.com.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dapperpanda.com.
        /// </summary>
        public static string WebsiteWithHttp {
            get {
                return ResourceManager.GetString("WebsiteWithHttp", resourceCulture);
            }
        }
    }
}
